.build:
  image: image-mirror-prod-registry.cloud.duke.edu/library/docker:20
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  stage: build
  script:
    - >
      docker build
      --file Dockerfile
      --pull
      -t "$CI_REGISTRY_IMAGE/${IMAGE_SLUG}:${IMAGE_TAG}"
      .
    - docker push "$CI_REGISTRY_IMAGE/${IMAGE_SLUG}:${IMAGE_TAG}"

build_image:
  variables:
    IMAGE_SLUG: $CI_PROJECT_NAME
    IMAGE_TAG: $CI_COMMIT_BRANCH
  extends: .build
