services:
  app:
    image: gitlab-registry.oit.duke.edu/codeplus/data-foundry-2023/data-foundry-2023-app:dockerize
    ports:
      - 3000:3000
    depends_on:
      - fastapi
    volumes:
      - type: bind
        source: ./data-foundry-app
        target: /code
  fastapi:
    image: gitlab-registry.oit.duke.edu/codeplus/data-foundry-2023/data-foundry-2023-fastapi:dockerize
    volumes:
      - type: bind
        source: ./data-foundry-fastapi
        target: /code
    env_file: ./data-foundry-fastapi/.env