kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app-route
  namespace: cli-deployment
spec:
  to:
    kind: Service
    name: shib-service
  port:
    targetPort: 8080
  tls:
    termination: edge